### PR TITLE
Make "Level 4" a header

### PR DESCRIPTION
**Pull request by agarrharr**

### CODE REVIEW

**Comment by prettydiff** [comment]
Accepted.  Thanks!

Please feel free to disagree and recommend changes, by the way.

**Comment by agarrharr** [comment]
Well, I'm not quite sure what this project is all about. If you added a readme describing the goals of the project, that would probably be helpful. I just saw that it was trending on github and that's why I was checking it out.

**Comment by prettydiff** [comment]
I can do that.  Where do you see github trending projects?

**Comment by agarrharr** [comment]
Here: https://github.com/trending

This repo is #2 today under unknown languages

https://github.com/trending/unknown

**Pull request merged**
